// ---------------------------------------------------------------
// Exporters: SQL (postgres/mysql/sqlite), MongoDB (Mongoose + JSON Schema
// validator), Prisma, TypeScript, JSON Schema, DBML, Markdown data dictionary
// ---------------------------------------------------------------

import { TYPE_MAP, topoOrder } from '../model/schema.js';

const rel = (project, r) => {
  const ft = project.tables.find(t => t.id === r.fromTable);
  const tt = project.tables.find(t => t.id === r.toTable);
  if (!ft || !tt) return null;
  const ff = ft.fields.find(f => f.id === r.fromField);
  const tf = tt.fields.find(f => f.id === r.toField);
  if (!ff || !tf) return null;
  return { ft, tt, ff, tf, kind: r.kind, onDelete: r.onDelete };
};

const relations = (project) => project.relations.map(r => rel(project, r)).filter(Boolean);

// ---------- SQL ----------
export function exportSQL(project, dialect = 'postgres') {
  const map = TYPE_MAP[dialect] || TYPE_MAP.postgres;
  const q = dialect === 'mysql' ? '`' : '"';
  const rels = relations(project);
  const out = [`-- ${project.meta.name} — generated by SchemaMind (16xbrains.com)`, `-- Dialect: ${dialect}`, ''];

  for (const t of topoOrder(project)) {
    const lines = [];
    for (const f of t.fields) {
      let type = map[f.type] || map.string;
      if (f.default === 'autoincrement') {
        if (dialect === 'postgres') type = f.type === 'bigint' ? 'BIGSERIAL' : 'SERIAL';
        else if (dialect === 'mysql') type += ' AUTO_INCREMENT';
        // sqlite: INTEGER PRIMARY KEY is auto-incrementing by itself
      }
      let line = `  ${q}${f.name}${q} ${type}`;
      if (f.pk && singlePk(t)) line += ' PRIMARY KEY';
      if (!f.nullable && !f.pk) line += ' NOT NULL';
      if (f.unique && !f.pk) line += ' UNIQUE';
      line += sqlDefault(f, dialect);
      if (f.type === 'enum' && f.enumValues.length && dialect === 'mysql')
        line = `  ${q}${f.name}${q} ENUM(${f.enumValues.map(v => `'${v}'`).join(', ')})` + (!f.nullable ? ' NOT NULL' : '');
      if (f.type === 'enum' && f.enumValues.length && dialect !== 'mysql')
        line += ` CHECK (${q}${f.name}${q} IN (${f.enumValues.map(v => `'${v}'`).join(', ')}))`;
      lines.push(line);
    }
    if (!singlePk(t)) {
      const pks = t.fields.filter(f => f.pk).map(f => `${q}${f.name}${q}`);
      if (pks.length) lines.push(`  PRIMARY KEY (${pks.join(', ')})`);
    }
    for (const r of rels.filter(r => r.ft.id === t.id)) {
      const od = r.onDelete === 'set null' ? 'SET NULL' : r.onDelete.toUpperCase();
      lines.push(`  FOREIGN KEY (${q}${r.ff.name}${q}) REFERENCES ${q}${r.tt.name}${q}(${q}${r.tf.name}${q}) ON DELETE ${od}`);
    }
    out.push(`CREATE TABLE ${q}${t.name}${q} (`, lines.join(',\n'), `);`, '');
    for (const f of t.fields.filter(f => f.indexed && !f.pk && !f.unique)) {
      out.push(`CREATE INDEX idx_${t.name}_${f.name} ON ${q}${t.name}${q} (${q}${f.name}${q});`);
    }
    if (t.fields.some(f => f.indexed && !f.pk && !f.unique)) out.push('');
  }
  return out.join('\n');
}

const singlePk = (t) => t.fields.filter(f => f.pk).length <= 1;

function sqlDefault(f, dialect) {
  if (f.default == null || f.default === '' || f.default === 'autoincrement') return '';
  if (f.default === 'now') return dialect === 'mysql' ? ' DEFAULT CURRENT_TIMESTAMP' : ' DEFAULT CURRENT_TIMESTAMP';
  if (f.default === 'uuid') return dialect === 'postgres' ? ' DEFAULT gen_random_uuid()' : '';
  if (/^-?\d+(\.\d+)?$/.test(f.default) || /^(true|false)$/i.test(f.default)) return ` DEFAULT ${f.default}`;
  return ` DEFAULT '${String(f.default).replace(/'/g, "''")}'`;
}

// ---------- MongoDB / Mongoose ----------
export function exportMongoose(project) {
  const rels = relations(project);
  const out = [`// ${project.meta.name} — Mongoose models generated by SchemaMind`, `const mongoose = require('mongoose');`, `const { Schema } = mongoose;`, ''];
  for (const t of project.tables) {
    const model = pascal(t.name);
    out.push(`const ${model}Schema = new Schema({`);
    for (const f of t.fields) {
      if (f.name === '_id' || (f.pk && f.name === 'id')) continue; // Mongo manages _id
      const fkRel = rels.find(r => r.ft.id === t.id && r.ff.id === f.id);
      if (fkRel) {
        out.push(`  ${camel(f.name)}: { type: Schema.Types.ObjectId, ref: '${pascal(fkRel.tt.name)}'${f.nullable ? '' : ', required: true'}${f.indexed ? ', index: true' : ''} },`);
        continue;
      }
      const mType = TYPE_MAP.mongoose[f.type] || 'String';
      const opts = [`type: ${mType}`];
      if (!f.nullable) opts.push('required: true');
      if (f.unique) opts.push('unique: true');
      if (f.indexed && !f.unique) opts.push('index: true');
      if (f.type === 'enum' && f.enumValues.length) opts.push(`enum: [${f.enumValues.map(v => `'${v}'`).join(', ')}]`);
      if (f.default === 'now') opts.push('default: Date.now');
      else if (f.default != null && f.default !== '' && f.default !== 'uuid' && f.default !== 'autoincrement')
        opts.push(`default: ${/^-?\d+(\.\d+)?$|^(true|false)$/i.test(f.default) ? f.default : `'${f.default}'`}`);
      out.push(`  ${camel(f.name)}: { ${opts.join(', ')} },`);
    }
    out.push(`}, { timestamps: true });`, '');
    out.push(`const ${model} = mongoose.model('${model}', ${model}Schema);`, '');
  }
  out.push(`module.exports = { ${project.tables.map(t => pascal(t.name)).join(', ')} };`);
  return out.join('\n');
}

export function exportMongoValidator(project) {
  const dbCommands = project.tables.map(t => {
    const required = t.fields.filter(f => !f.nullable && !(f.pk && f.name === 'id')).map(f => camel(f.name));
    const properties = {};
    for (const f of t.fields) {
      if (f.pk && f.name === 'id') continue;
      const bson = { uuid: 'string', int: 'int', bigint: 'long', float: 'double', decimal: 'decimal', string: 'string', text: 'string', boolean: 'bool', date: 'date', datetime: 'date', time: 'string', json: 'object', binary: 'binData', enum: 'string' }[f.type] || 'string';
      properties[camel(f.name)] = { bsonType: f.nullable ? [bson, 'null'] : bson, description: f.note || undefined };
      if (f.type === 'enum' && f.enumValues.length) properties[camel(f.name)].enum = f.enumValues;
    }
    return { collection: t.name, validator: { $jsonSchema: { bsonType: 'object', required: required.length ? required : undefined, properties } } };
  });
  const lines = [`// MongoDB collection validators — run in mongosh`, ''];
  for (const c of dbCommands) {
    lines.push(`db.createCollection(${JSON.stringify(c.collection)}, {`, `  validator: ${JSON.stringify(c.validator, null, 2).split('\n').join('\n  ')}`, `});`, '');
  }
  return lines.join('\n');
}

// ---------- Prisma ----------
export function exportPrisma(project) {
  const rels = relations(project);
  const out = [`// ${project.meta.name} — Prisma schema generated by SchemaMind`, '', 'datasource db {', '  provider = "postgresql"', '  url      = env("DATABASE_URL")', '}', '', 'generator client {', '  provider = "prisma-client-js"', '}', ''];
  // enums
  const enums = [];
  for (const t of project.tables) for (const f of t.fields) {
    if (f.type === 'enum' && f.enumValues.length) {
      const en = pascal(t.name) + pascal(f.name);
      enums.push(`enum ${en} {\n${f.enumValues.map(v => '  ' + v.replace(/[^\w]/g, '_')).join('\n')}\n}`);
    }
  }
  out.push(...enums, enums.length ? '' : null);

  for (const t of project.tables) {
    out.push(`model ${pascal(t.name)} {`);
    for (const f of t.fields) {
      let type = f.type === 'enum' && f.enumValues.length ? pascal(t.name) + pascal(f.name) : (TYPE_MAP.prisma[f.type] || 'String');
      const fkRel = rels.find(r => r.ft.id === t.id && r.ff.id === f.id);
      let attrs = '';
      if (f.pk) attrs += ' @id' + (f.default === 'uuid' ? ' @default(uuid())' : f.default === 'autoincrement' ? ' @default(autoincrement())' : '');
      if (f.unique && !f.pk) attrs += ' @unique';
      if (f.default === 'now') attrs += ' @default(now())';
      else if (f.default != null && f.default !== '' && !['uuid', 'autoincrement', 'now'].includes(f.default) && !f.pk)
        attrs += ` @default(${/^-?\d+(\.\d+)?$|^(true|false)$/i.test(f.default) ? f.default : `"${f.default}"`})`;
      out.push(`  ${camel(f.name)} ${type}${f.nullable && !f.pk ? '?' : ''}${attrs}`);
      if (fkRel) {
        out.push(`  ${camel(fkRel.tt.name)} ${pascal(fkRel.tt.name)}${f.nullable ? '?' : ''} @relation(fields: [${camel(f.name)}], references: [${camel(fkRel.tf.name)}])`);
      }
    }
    // reverse sides
    for (const r of rels.filter(r => r.tt.id === t.id && r.ft.id !== t.id)) {
      const many = r.kind !== 'one-one';
      out.push(`  ${camel(r.ft.name)}${many ? 's' : ''} ${pascal(r.ft.name)}${many ? '[]' : '?'}`);
    }
    out.push('}', '');
  }
  return out.filter(l => l !== null).join('\n');
}

// ---------- TypeScript ----------
export function exportTypeScript(project) {
  const rels = relations(project);
  const out = [`// ${project.meta.name} — TypeScript types generated by SchemaMind`, ''];
  for (const t of project.tables) {
    for (const f of t.fields) if (f.type === 'enum' && f.enumValues.length)
      out.push(`export type ${pascal(t.name)}${pascal(f.name)} = ${f.enumValues.map(v => `'${v}'`).join(' | ')};`);
  }
  out.push('');
  for (const t of project.tables) {
    if (t.note) out.push(`/** ${t.note} */`);
    out.push(`export interface ${pascal(t.name)} {`);
    for (const f of t.fields) {
      const type = f.type === 'enum' && f.enumValues.length ? `${pascal(t.name)}${pascal(f.name)}` : (TYPE_MAP.typescript[f.type] || 'string');
      if (f.note) out.push(`  /** ${f.note} */`);
      out.push(`  ${camel(f.name)}${f.nullable ? '?' : ''}: ${type};`);
    }
    for (const r of rels.filter(r => r.tt.id === t.id && r.ft.id !== t.id)) {
      out.push(`  ${camel(r.ft.name)}${r.kind !== 'one-one' ? 's' : ''}?: ${pascal(r.ft.name)}${r.kind !== 'one-one' ? '[]' : ''};`);
    }
    out.push('}', '');
  }
  return out.join('\n');
}

// ---------- JSON Schema ----------
export function exportJSONSchema(project) {
  const defs = {};
  for (const t of project.tables) {
    const props = {};
    const required = [];
    for (const f of t.fields) {
      const js = { type: TYPE_MAP.jsonschema[f.type] || 'string' };
      if (f.type === 'datetime') js.format = 'date-time';
      if (f.type === 'date') js.format = 'date';
      if (f.type === 'uuid') js.format = 'uuid';
      if (f.type === 'enum' && f.enumValues.length) js.enum = f.enumValues;
      if (f.note) js.description = f.note;
      props[f.name] = f.nullable ? { anyOf: [js, { type: 'null' }] } : js;
      if (!f.nullable) required.push(f.name);
    }
    defs[t.name] = { type: 'object', title: pascal(t.name), description: t.note || undefined, properties: props, required: required.length ? required : undefined, additionalProperties: false };
  }
  return JSON.stringify({ $schema: 'https://json-schema.org/draft/2020-12/schema', title: project.meta.name, $defs: defs }, null, 2);
}

// ---------- DBML ----------
export function exportDBML(project) {
  const out = [`// ${project.meta.name} — DBML generated by SchemaMind`, ''];
  for (const t of project.tables) {
    out.push(`Table ${t.name} {`);
    for (const f of t.fields) {
      const settings = [];
      if (f.pk) settings.push('pk');
      if (f.unique) settings.push('unique');
      if (!f.nullable && !f.pk) settings.push('not null');
      if (f.default === 'now') settings.push('default: `now()`');
      else if (f.default && f.default !== 'uuid' && f.default !== 'autoincrement') settings.push(`default: '${f.default}'`);
      if (f.note) settings.push(`note: '${f.note}'`);
      out.push(`  ${f.name} ${f.type === 'enum' ? 'varchar' : f.type}${settings.length ? ` [${settings.join(', ')}]` : ''}`);
    }
    if (t.note) out.push(`  Note: '${t.note}'`);
    out.push('}', '');
  }
  for (const r of relations(project)) {
    const op = r.kind === 'one-one' ? '-' : r.kind === 'many-many' ? '<>' : '>';
    out.push(`Ref: ${r.ft.name}.${r.ff.name} ${op} ${r.tt.name}.${r.tf.name}`);
  }
  return out.join('\n');
}

// ---------- Markdown data dictionary ----------
export function exportMarkdown(project) {
  const rels = relations(project);
  const out = [`# ${project.meta.name}`, '', `> Data dictionary generated by SchemaMind — ${new Date().toISOString().slice(0, 10)}`, ''];
  if (project.notes) out.push(project.notes, '');
  out.push(`**Tables:** ${project.tables.length} · **Relations:** ${project.relations.length}`, '');
  for (const t of project.tables) {
    out.push(`## ${t.name}`, '');
    if (t.note) out.push(t.note, '');
    out.push('| Field | Type | Constraints | Default | Notes |', '|---|---|---|---|---|');
    for (const f of t.fields) {
      const cons = [f.pk && 'PK', f.unique && 'unique', !f.nullable && 'not null', f.indexed && 'indexed'].filter(Boolean).join(', ');
      const type = f.type === 'enum' && f.enumValues.length ? `enum(${f.enumValues.join(', ')})` : f.type;
      out.push(`| ${f.name} | ${type} | ${cons || '—'} | ${f.default ?? '—'} | ${f.note || '—'} |`);
    }
    const trels = rels.filter(r => r.ft.id === t.id || r.tt.id === t.id);
    if (trels.length) {
      out.push('', '**Relations:**', '');
      for (const r of trels) out.push(`- \`${r.ft.name}.${r.ff.name}\` ${r.kind} → \`${r.tt.name}.${r.tf.name}\` (on delete: ${r.onDelete})`);
    }
    out.push('');
  }
  return out.join('\n');
}

// ---------- helpers ----------
export const pascal = (s) => String(s).split(/[_\s-]+/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
export const camel = (s) => { const p = pascal(s); return p.charAt(0).toLowerCase() + p.slice(1); };

export const EXPORT_FORMATS = [
  { id: 'sql-postgres', label: 'SQL — PostgreSQL', ext: 'sql', fn: (p) => exportSQL(p, 'postgres') },
  { id: 'sql-mysql', label: 'SQL — MySQL', ext: 'sql', fn: (p) => exportSQL(p, 'mysql') },
  { id: 'sql-sqlite', label: 'SQL — SQLite', ext: 'sql', fn: (p) => exportSQL(p, 'sqlite') },
  { id: 'mongoose', label: 'MongoDB — Mongoose models', ext: 'js', fn: exportMongoose },
  { id: 'mongo-validator', label: 'MongoDB — collection validators', ext: 'js', fn: exportMongoValidator },
  { id: 'prisma', label: 'Prisma schema', ext: 'prisma', fn: exportPrisma },
  { id: 'typescript', label: 'TypeScript interfaces', ext: 'ts', fn: exportTypeScript },
  { id: 'jsonschema', label: 'JSON Schema', ext: 'json', fn: exportJSONSchema },
  { id: 'dbml', label: 'DBML (dbdiagram.io)', ext: 'dbml', fn: exportDBML },
  { id: 'markdown', label: 'Markdown data dictionary', ext: 'md', fn: exportMarkdown }
];
